app:
  port: 3000

db:
  driver: "mysql"
  username: root
  password: 12345678
  database: infinite-travel


appAuth : 
  tokenSecret: "secret"  


s3:
  bucketName: "infinite-travel"
  region: "ap-southeast-1"
  accessKeyId: "AKIA3IA7PUU6LUKZFSE3"
  accessSecretKey: "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"    